version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    image: laneup-api
    build:
      context: ../api/
    depends_on:
      - db
    ports:
      - 3001:3001
      - 8082:8082
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASS: postgres
      DB_PORT: 5432
      PUBLIC_WS_URL: /
      PUBLIC_WS_PORT: 8082
      API_SERVER: /
      SET_HTTPS: 0
      PORT: 3001
      MSG_TWILIO_COUNTRY_CODE:
      MSG_TWILIO_ACCT_ID:
      MSG_TWILIO_ACCT_TOKEN:
      MSG_TWILIO_NUMBER:
volumes:
  db:
    driver: local